### PR TITLE
don't escape the title of the composer

### PR DESCRIPTION
**Pull request by BenLubar**

### CODE REVIEW

**Comment by BenLubar** [comment]
With this I think we should be all ready for NodeBB/nodebb-plugin-composer-default#30

**Comment by RaceProUK** [comment]
Not quite; there's two places you need to escape the title, and this change only does one of them

**Comment by BenLubar** [comment]
The one that's escaped in this commit is the one in the editor content. The other one is the title of the editor, which ends up with backslashes in it.

**Comment by RaceProUK** [comment]
There's a second path that also sets editor content, about a half-dozen lines after

**Pull request merged**
